version: '3.9'

services:
  # 🔐 AuthService - doar autentificare + JWT
  authservice:
    build: ./AuthService
    ports:
      - "5001:8080"
    depends_on:
      - userdataservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app_net

  # 👤 UserDataService - gestionează datele utilizatorilor (DB + API)
  userdataservice:
    build: ./UserDataService
    ports:
      - "5002:8080"
    depends_on:
      - db-users
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app_net

  # 🗃️ Baza de date pentru UserDataService
  db-users:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usersdb
    volumes:
      - users_pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app_net

  tripplannerservice:
    build: ./TripPlannerService
    ports:
      - "5003:8080"
    depends_on:
      - db-trip
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app_net

  db-trip:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tripdb
    ports:
      - "5434:5432"
    volumes:
      - trip_pgdata:/var/lib/postgresql/data
    networks:
      - app_net



networks:
  app_net:

volumes:
  users_pgdata:
  trip_pgdata:

